// kob-master/web/src/components/NavBar.vue
<template>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <!--将a标签换为router-link,可以在页面内部切换界面而不刷新-->
    <router-link  class="navbar-brand" :to="{name: 'home'}">Snake fighting field</router-link>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <router-link :class="route_name == 'pk_index'? 'nav-link active' : 'nav-link' " :to = "{name: 'pk_index'}">对局</router-link>
        </li>
        <li class="nav-item">
          <router-link :class="route_name == 'record_index' ? 'nav-link active' : 'nav-link'" :to = "{name :'record_index'}">对局列表</router-link>
        </li>
        <li class="nav-item">
          <router-link :class = "route_name == 'ranklist_index' ? 'nav-link active' : 'nav-link'" :to = "{name: 'ranklist_index'}">排行榜</router-link>
        </li>
        <li class="nav-item">
          <router-link :class = "route_name == 'instruction_index' ? 'nav-link active' : 'nav-link'" :to = "{name: 'instruction_index'}">游戏规则</router-link>
        </li>
      </ul>
      <ul class="navbar-nav" v-if="$store.state.user.is_login">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            {{ $store.state.user.username}}
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li>
              <router-link class="dropdown-item" :to="{name: 'user_bot_index'}">我的bot</router-link>
            </li>

            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#" @click="logout">退出</a></li>
          </ul>
        </li>

      </ul>
      <ul class="navbar-nav" v-else-if="!$store.state.user.pulling_info">
        <li class="nav-item "> <!--点击跳转链接用router-link, 同时用：to绑定路由名-->
          <router-link class="nav-link " :to="{name: 'user_account_login'}" role="button" >
            登录
          </router-link>
        </li>
        <li class="nav-item ">
          <router-link class="nav-link " :to="{name: 'user_account_register'}" role="button" d>
            注册
          </router-link>
        </li>
      </ul>
    </div>
  </div>
</nav>
</template>

<script>
import { useRoute } from 'vue-router'
import { computed } from 'vue' //实时计算更新
import { useStore } from 'vuex';
export default {
    setup() {
        const store = useStore();
        const route = useRoute(); //useRouter()获取当前页面
        let route_name = computed(() => route.name)

        //退出事件绑定事件
        const logout = () => {
          store.dispatch("logout");
        }
        return {
            route_name,
            logout
        }
    }
}
</script>

<style scoped>

</style>

// route-app/src/components/navbar.jsx
import React, { Component } from 'react';
import {Link} from 'react-router-dom';

class NavBar extends Component {
    state = {  } 
    render() { 
        return (
            <nav className="navbar navbar-expand-lg bg-body-tertiary">
            <div className="container-fluid">
                <Link className="navbar-brand" to = "/">Section</Link>
                <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span className="navbar-toggler-icon"></span>
                </button>
                <div className="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div className="navbar-nav">
                    <Link className="nav-link active" to = "/">Home</Link>
                    <Link className="nav-link" to = "/linux">Linux</Link>
                    <Link className="nav-link" to = "/django">Django</Link>
                    <Link className="nav-link" to = "/web">Web</Link>
                </div>
                </div>
            </div>
            </nav>
        );
    }
}
 
export default NavBar;
